AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: StepFunction Page

Parameters:
  ApplicationName:
    Type: String
    Default: 'StepFunctionPage'

Resources:
  FrontPageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: StepFunctionPageApi
      EndpointConfiguration: REGIONAL
      StageName: Prod
  FrontPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: StepFunctionPageFunction
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: target/lambda/stepfunction/
      MemorySize: 256
      Architectures: ["arm64"]
      Description: 'StepFunction Function'
      Policies: AWSStepFunctionsReadOnlyAccess
      Events:
        testapi:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RestApiId: !Ref FrontPageApi

Outputs:
  FunctionName:
    Value: !Ref FrontPageFunction
    Description: Name of the Lambda function
  APIURI:
    Description: "URI"
    Value: !Join [ '', [ 'https://', !Ref FrontPageApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/','Prod/'] ]
